group: forge
steps:
  - name: forge
    wanda: ci/docker/forge.wanda.yaml

  # Images for building executable and docker images

  - name: manylinux
    wanda: ci/docker/manylinux.wanda.yaml

  - name: raypy38cu118base
    wanda: ci/docker/ray.py38.cu118.base.wanda.yaml

  - name: raypy38gpubase
    wanda: ci/docker/ray.py38.gpu.base.wanda.yaml
    depends_on: raypy38cu118base

  # Image for running tests
  
  - name: oss-ci-base_test
    wanda: ci/docker/base.test.wanda.yaml
  
  - name: oss-ci-base_build
    wanda: ci/docker/base.build.wanda.yaml
    depends_on: oss-ci-base_test

  - name: oss-ci-base_ml
    wanda: ci/docker/base.ml.wanda.yaml
    depends_on: oss-ci-base_test

  - name: corebuild
    wanda: ci/docker/core.build.wanda.yaml
    depends_on: oss-ci-base_build

  - name: servebuild
    wanda: ci/docker/serve.build.wanda.yaml
    depends_on: oss-ci-base_build

  - name: serverlessbuild
    wanda: ci/docker/serverless.build.wanda.yaml
    depends_on: oss-ci-base_build
