group: build
steps:
  - label: ":tapioca: build: wheel {{matrix}}"
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build -- wheel --python-version {{matrix}}
    matrix:
      - py37
      - py38
      - py39
      - py310
      - py311
    depends_on: 
      - manylinux
      - forge
    job_env: forge

  - label: ":tapioca: build: jar"
    instance_type: medium
    commands:
      - ./ci/build/build-manylinux-ray.sh
      - ./ci/build/build-manylinux-jar.sh
      - ./ci/build/copy_build_artifacts.sh jar
    depends_on: manylinux
    job_env: manylinux

  - label: ":tapioca: build: ray cu118 docker"
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build -- docker --python-version py38 --platform cu118
    depends_on: 
      - manylinux
      - forge
      - raypy38cu118base
    job_env: forge

  - label: ":tapioca: build: ray gpu docker"
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build -- docker --python-version py38 --platform gpu
    depends_on: 
      - manylinux
      - forge
      - raypy38cu118base
    job_env: forge
