name: "raypy38gpubase"
froms: ["cr.ray.io/rayproject/raypy38cu118base"]
dockerfile: docker/ray-ml/Dockerfile
srcs:
  - python/requirements.txt
  - python/requirements_compiled.txt
  - python/requirements/ml/dl-cpu-requirements.txt
  - python/requirements/ml/dl-gpu-requirements.txt
  - python/requirements/ml/core-requirements.txt
  - python/requirements/ml/data-requirements.txt
  - python/requirements/ml/rllib-requirements.txt
  - python/requirements/ml/rllib-test-requirements.txt
  - python/requirements/ml/train-requirements.txt
  - python/requirements/ml/train-test-requirements.txt
  - python/requirements/ml/tune-requirements.txt
  - python/requirements/ml/tune-test-requirements.txt
  - python/requirements/docker/ray-docker-requirements.txt
  - docker/ray-ml/install-ml-docker-requirements.sh
build_args:
  - FROM=cr.ray.io/rayproject/raypy38cu118base
  - REQUIREMENT_PATH=python
  - DOCKER_REQUIREMENT_PATH=python/requirements/docker
  - ML_REQUIREMENT_PATH=python/requirements/ml
  - SCRIPT_PATH=docker/ray-ml
tags:
  - cr.ray.io/rayproject/raypy38gpubase
